### ISSUE TITLE
Switch color-name library?

### ISSUE THREAD

**Issue by ntwb** [dustinspecker/is-css-color-name#28]
Hey, wondering if you would you be up for switching the color-name library you use?

Currently your using: https://www.npmjs.com/package/css-color-names using [css-color-names.json](https://github.com/bahamas10/css-color-names/blob/master/css-color-names.json)

Proposed library: https://www.npmjs.com/package/color-names using [color-names.json](https://github.com/jonathantneal/color-names/blob/master/color-names.json)

The end goal here is two fold:

1. There are 2,332 colors in the proposed library over the current 148
2. Accuracy, as to which `green` is actually `green` I'm not sure  ¯\\_(ツ)_/¯

 • Current `green` is [defined](https://github.com/bahamas10/css-color-names/blob/master/css-color-names.json#L56) as `#008000`

 • Proposed `green` is [defined](https://github.com/jonathantneal/color-names/blob/master/color-names.json#L912) as `#00ff00` 

 • [CSSWG](https://drafts.csswg.org/css-color-4/#valdef-color-green) defines `green` as `#008000`

**Comment by dustinspecker** [comment]
Hey. I would like the main intent of this library to focus on following CSSWG, but I'm open to other opinions if that seems to be a poor stance.

If stylelint decides they want the other color list, then I am also open to discussing the idea of allowing a configuration for setting the color list to use.

**Comment by ntwb** [comment]
Thanks, I've dug around and researched a little more and as mentioned in stylelint these other colors do not work in browsers so the "formal" list of W3c/CSSWG's ~148 colors should be whats used here :smile: 

FYI: I did find the difference in greens is an X11/W3C conflict, documented [here](https://en.wikipedia.org/wiki/X11_color_names)
